import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import { registerSW } from "virtual:pwa-register";
import App from "./App";
import "./index.css";

// Registers the service worker generated by vite-plugin-pwa so the app
// works offline / installs as a PWA. Silently no-ops in dev unless the
// plugin's devOptions are enabled.
registerSW({ immediate: true });

createRoot(document.getElementById("root")).render(
  <StrictMode>
    <App />
  </StrictMode>,
);
