import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import { registerSW } from "virtual:pwa-register";
import App from "./App";
import "./index.css";

// Registers the service worker generated by vite-plugin-pwa so the app
// works offline / installs as a PWA. Silently no-ops in dev unless the
// plugin's devOptions are enabled.
//
// `registerType: "autoUpdate"` (vite.config.js) only swaps which service
// worker is *installed* in the background — it does NOT reload an already
// open tab, so a tab left open across a deploy keeps running the old JS
// (old bugs and all) until the user manually closes and reopens the app.
// Calling updateSW(true) as soon as a new version is found makes that
// update apply immediately instead of requiring a manual restart.
const updateSW = registerSW({
  immediate: true,
  onNeedRefresh() {
    updateSW(true);
  },
});

createRoot(document.getElementById("root")).render(
  <StrictMode>
    <App />
  </StrictMode>,
);
